# Generated by Django 5.1.8 on 2025-10-15 06:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_type', models.CharField(choices=[('tenant_admin', 'Client Admin/Owner'), ('branch_manager', 'Branch Manager'), ('loan_officer', 'Loan Officer'), ('member', 'Member')], max_length=20)),
                ('staff_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('allowed_apps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('allowed_actions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('pin_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('pin_salt', models.CharField(blank=True, max_length=64, null=True)),
                ('pin_attempts', models.PositiveIntegerField(default=0)),
                ('pin_locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_attempt', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('global_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_users',
                'indexes': [models.Index(fields=['phone_number'], name='tenant_user_phone_n_090477_idx'), models.Index(fields=['user_type'], name='tenant_user_user_ty_a7f342_idx'), models.Index(fields=['staff_id'], name='tenant_user_staff_i_54f0b4_idx'), models.Index(fields=['global_user'], name='tenant_user_global__803e21_idx')],
            },
        ),
    ]
