# Generated by Django 5.1.8 on 2025-10-15 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('super_admin', 'Super Admin'), ('platform_staff', 'Platform Staff'), ('tenant_admin', 'Tenant Admin'), ('tenant_member', 'Tenant Member')], default='platform_staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('tenant_id', models.CharField(blank=True, help_text='Tenant identifier for tenant users', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for tenant user authentication', max_length=15, null=True)),
                ('tenant_role', models.CharField(blank=True, help_text='Specific role: owner, branch_manager, loan_officer, member', max_length=20, null=True)),
                ('is_phone_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_email_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'global_users',
                'indexes': [models.Index(fields=['email'], name='global_user_email_04c0d8_idx'), models.Index(fields=['user_type'], name='global_user_user_ty_117e55_idx'), models.Index(fields=['tenant_id'], name='global_user_tenant__14c035_idx'), models.Index(fields=['phone_number'], name='global_user_phone_n_00a79e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tenant_id__isnull', False)), fields=('phone_number', 'tenant_id'), name='unique_phone_per_tenant'), models.CheckConstraint(condition=models.Q(('user_type__in', ['super_admin', 'platform_staff']), models.Q(('phone_number__isnull', False), ('tenant_id__isnull', False), ('user_type__in', ['tenant_admin', 'tenant_member'])), _connector='OR'), name='tenant_users_have_required_fields')],
            },
        ),
    ]
