# Generated by Django 4.2.11 on 2025-10-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city_of_origin',
            field=models.CharField(default='Nairobi', max_length=180, verbose_name='City'),
        ),
    ]
